/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as LayerSolverRouteImport } from './routes/layer-solver'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainersIndexRouteImport } from './routes/trainers/index'
import { Route as TrainersNsCenterRouteImport } from './routes/trainers/ns-center'
import { Route as TrainersNsCaseRouteImport } from './routes/trainers/ns-case'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const LayerSolverRoute = LayerSolverRouteImport.update({
  id: '/layer-solver',
  path: '/layer-solver',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIndexRoute = TrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersNsCenterRoute = TrainersNsCenterRouteImport.update({
  id: '/trainers/ns-center',
  path: '/trainers/ns-center',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersNsCaseRoute = TrainersNsCaseRouteImport.update({
  id: '/trainers/ns-case',
  path: '/trainers/ns-case',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/layer-solver': typeof LayerSolverRoute
  '/trainer': typeof TrainerRoute
  '/trainers/ns-case': typeof TrainersNsCaseRoute
  '/trainers/ns-center': typeof TrainersNsCenterRoute
  '/trainers/': typeof TrainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/layer-solver': typeof LayerSolverRoute
  '/trainer': typeof TrainerRoute
  '/trainers/ns-case': typeof TrainersNsCaseRoute
  '/trainers/ns-center': typeof TrainersNsCenterRoute
  '/trainers': typeof TrainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/layer-solver': typeof LayerSolverRoute
  '/trainer': typeof TrainerRoute
  '/trainers/ns-case': typeof TrainersNsCaseRoute
  '/trainers/ns-center': typeof TrainersNsCenterRoute
  '/trainers/': typeof TrainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/layer-solver'
    | '/trainer'
    | '/trainers/ns-case'
    | '/trainers/ns-center'
    | '/trainers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/layer-solver'
    | '/trainer'
    | '/trainers/ns-case'
    | '/trainers/ns-center'
    | '/trainers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/layer-solver'
    | '/trainer'
    | '/trainers/ns-case'
    | '/trainers/ns-center'
    | '/trainers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LayerSolverRoute: typeof LayerSolverRoute
  TrainerRoute: typeof TrainerRoute
  TrainersNsCaseRoute: typeof TrainersNsCaseRoute
  TrainersNsCenterRoute: typeof TrainersNsCenterRoute
  TrainersIndexRoute: typeof TrainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layer-solver': {
      id: '/layer-solver'
      path: '/layer-solver'
      fullPath: '/layer-solver'
      preLoaderRoute: typeof LayerSolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/': {
      id: '/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof TrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/ns-center': {
      id: '/trainers/ns-center'
      path: '/trainers/ns-center'
      fullPath: '/trainers/ns-center'
      preLoaderRoute: typeof TrainersNsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/ns-case': {
      id: '/trainers/ns-case'
      path: '/trainers/ns-case'
      fullPath: '/trainers/ns-case'
      preLoaderRoute: typeof TrainersNsCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LayerSolverRoute: LayerSolverRoute,
  TrainerRoute: TrainerRoute,
  TrainersNsCaseRoute: TrainersNsCaseRoute,
  TrainersNsCenterRoute: TrainersNsCenterRoute,
  TrainersIndexRoute: TrainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
