name: Test and Deploy to Github Pages

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/playwright.yml
  build-and-deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Static Site
        run: npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "dist/client"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
